### ISSUE TITLE
Using iron-icons with mat-icon

### ISSUE THREAD

**Issue by niknetniko** [expandjs/mat-icon#1]
Hi! I was wondering if it would be possible to use icons from the iron-icons set with mat-icon?

The reason is that I mainly use the polymer paper elements, and I use the mat elements when the paper ones don't work or do not provide the features I want. However, due to this, I currently have to load the mat-icons and the iron-icons. That seems a little silly, as most of the icons are the same. So I was wondering if there could be some fallback, or a prefix (iron:blabla?) or something to use the iron icons.

**Comment by Pupix** [comment]
At the moment this isn't possible. Polymer and us have 2 different approaches about the icons (this is an inherit problem of Web Components dependency management). They use `<iron-iconset-svg>` to create the icons and `<iron-meta>` to fetch them, we have  `<xp-iconset>` to create and fetch them.

This means that either us should use `<iron-meta>` and add/overwrite any different icons or they should use `<xp-iconset>`. Neither of which is a valid option, because tomorrow someone could come up and say _"I use this other icon set from another library, can you add it?"_. At that point either everybody gets locked using `<iron-meta>` when creating an icon element or everybody needs to know what other icon libraries are out there and provide support for them.

My suggestion would be to use minimal amount of icons needed so you can have `device-icons` coming from `mat-icons` and `navigation-icons` coming from `iron-icons` for example. This way you don't overlap the icons and increase and final filesize of your project.

**Comment by niknetniko** [comment]
OK, thanks!
